### ISSUE TITLE
bspatch so的源代码提供么

### ISSUE THREAD

**Issue by shizhy1986** [zzz40500/Tinker_imitator#3]

**Comment by shoyu666** [comment]
bspatch so https://github.com/shoyu666/bsdiffAndroidDemo

**Comment by shizhy1986** [comment]
楼上的代码我试了下对dex先生成patch然后对老的dex进行patch后结果不对的，不知道哪里出了问题

**Comment by zzz40500** [comment]
@shizhy1986  我参考 https://github.com/brok1n/androidBsdiffUpdate 这个的

**Comment by shizhy1986** [comment]
@zzz40500 你是有修改么，试了下他的库对dex打patch好像dex也是异常的，但你的库是可以得

**Comment by shizhy1986** [comment]
可以了，这个方案不错，持续关注
