### ISSUE TITLE
无法打补丁包

### ISSUE THREAD

**Issue by caijingfile** [zzz40500/Tinker_imitator#5]
在打补丁包这步，我现在android studio是2.1.2版本，没有你截图上那个按钮了。想了好久实在想不到那个按钮是什么功能去了。能否告知在新版本的as上是怎么操作了？

**Comment by zzz40500** [comment]
要安装插件。插件地址在readme中

**Comment by caijingfile** [comment]
bsdiff这个吗？我已经装了。是我找不到这个按钮
https://camo.githubusercontent.com/f02d71c09d4ab53b61b2a80d8dde46c46fa6eabf/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f3136363836362d336237333139623236626165653763372e706e673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430
让它生成补丁文件patchclasses.dex文件，我也试着直接在terminal里面运行bsdiff命令bsdiff oldfile newfile patchfile  但生成的不是dex文件，所以还是得找到你生成补丁包的方法。

**Comment by anoreg** [comment]
在代码的plugin目录, 然后在as的中安装plugin目录中zip中的jar, 方法同按张gsonformat一样

**Comment by caijingfile** [comment]
谢了！自己笨了没注意到这个插件，现在可以了。我还想问个问题，咋们一般项目都是一个dex文件。你源码中生成了classes.dex和classes2.dex两个dex。这种主动分割dex的代码是放在哪了。我也想学习学习。……^_^

**Comment by zzz40500** [comment]
在buildsrc中MultiDexAndroidBuilder 这个类
